import Navbar from "@/components/ui/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/ui/Footer";
import StoreProvider from "@/providers/StoreProvider";
import PersistStoreProvider from "@/providers/PersistStoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <PersistStoreProvider>
            <Navbar />
            <main className="mx-3 max-w-[1500px] 2xl:m-auto">{children}</main>
            <Footer />
          </PersistStoreProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
